"""Scenario Manager package for medical receptionist testing."""

from .enums import (
    DisclosureTiming,
    EvaluationCriterionType,
    FactSensitivity,
    ObjectivePriority,
    ReceptionistBehaviorImportance,
    SafetyClassification,
    ScenarioCategory,
    ScenarioLifecycle,
    TerminationReason,
    ValidationSeverity,
)
from .errors import (
    ScenarioValidationError,
    ScenarioValidationIssue,
    ScenarioValidationResult,
)
from .manager import ScenarioManager
from .models import (
    ControlledVariation,
    ConversationBehavior,
    DisclosureRule,
    EvaluationCriterion,
    ExpectedReceptionistBehavior,
    PatientFact,
    ProhibitedReceptionistBehavior,
    ResolvedVariation,
    SafetyPolicy,
    ScenarioIdentity,
    ScenarioInstance,
    ScenarioObjective,
    ScenarioTemplate,
    SyntheticPatientProfile,
    TerminationRule,
    VariationOption,
)
from .policies import DEFAULT_VALIDATION_POLICY, ScenarioValidationPolicy

__all__ = [
    "ControlledVariation",
    "ConversationBehavior",
    "DEFAULT_VALIDATION_POLICY",
    "DisclosureRule",
    "DisclosureTiming",
    "EvaluationCriterion",
    "EvaluationCriterionType",
    "ExpectedReceptionistBehavior",
    "FactSensitivity",
    "ObjectivePriority",
    "PatientFact",
    "ProhibitedReceptionistBehavior",
    "ReceptionistBehaviorImportance",
    "ResolvedVariation",
    "SafetyClassification",
    "SafetyPolicy",
    "ScenarioCategory",
    "ScenarioIdentity",
    "ScenarioInstance",
    "ScenarioLifecycle",
    "ScenarioManager",
    "ScenarioObjective",
    "ScenarioTemplate",
    "ScenarioValidationError",
    "ScenarioValidationIssue",
    "ScenarioValidationPolicy",
    "ScenarioValidationResult",
    "SyntheticPatientProfile",
    "TerminationReason",
    "TerminationRule",
    "ValidationSeverity",
    "VariationOption",
]
